Tic tac toe finished
bouaik/Tic-tac-toe-js pull request #1
Opened 2020-09-09 16:17 UTC by bouaik

## Multiplayer tic tac toe 
- players can put their names
- players can create a new game after finishing a game

2020-09-09 21:53 UTC, mosaaleb requested changes
#### Well done @bouaik :clap:

The gameplay is very nice, and doesn't have any bugs. Very well done. Yet there are other requirements related to code organization that needs to be met before moving on:

- [ ] The goal of this project is to make use of modules and factory functions and expose specific api functions for other modules to interact with it. Your code is organized but we need to use modules and factory functions patterns to get this project approved.

- [ ] It has game, gameBoard, player objects

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/objects_requirement.png)

You have only created player object using factory functions. But we need a to use the module pattern to encapsulate functionality for `Game` and `GameBoard`. Again, you can use module pattern if it's only one thing you are creating i.e. (Game, GameBoard), and factory function pattern -- like you did -- with objects that can be created more than once.


**To Summarize the requirements**:

- You need to use module pattern for creating `Game` and `GameBoard`. You can start by asking yourself some question about each one of these and what methods each module should have. For example: Game should have a method to check if we have reached an endgame position. `GameBoard` should have method to check if a cell is occupied or not, the array board should be defined in `GameBoard`. That way everything is encapsulated and our code is more organized.

Please handle these requirements and submit a new code review.
Feel free to contact me on Slack if you have any questions

##### Muhammad Ebeid

2020-09-09 21:53 UTC, mosaaleb commented on README.md
> +- Both players can put thier names
- [ ] Typo in `thier`

2020-09-09 21:53 UTC, mosaaleb commented on app.js
> +let gameState = ['', '', '', '', '', '', '', '', ''];
- [ ] **[OPTIONAL]** We can use array class initialization to have more idiomatic, less repititive code: 

```js
let gameState = new Array(9).fill('');

2020-09-09 21:53 UTC, mosaaleb commented on app.js
> +const playerOne = new Player('', 'X');
- [ ] It doesn't use global code - encapsulate logic inside modules or factories

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/global_requirement.png)

2020-09-09 21:53 UTC, mosaaleb commented on app.js
> +const statusDisplay = document.querySelector('.game--status');
- [ ] It doesn't use global code. Let's encapsulate all DOM functionalities inside its own module, and expose it's api function for other modules to use. Creating a module for the DOM functionality is also very important for separating code logic from dom manipulation. See next point
 
- [ ] Keep the application logic separated from DOM manipulation tasks
![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png)

2020-09-09 21:53 UTC, mosaaleb commented on app.js
> +  const clickedCell = clickedCellEvent.target;
- [ ] It has a function with the only responsibility of rendering the contents of the gameboard array to the webpage. 

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/render_requirement.png)

handleCellClick is doing too much, it listens for cell click, and then with the help of `handleCellPlayed` will update the board array, and then updating the dom (game logic is not separated from dom manipulation)

2020-09-10 10:17 UTC, bouaik commented
## Changes Implemented
- create factory function for Board, Game, Player
- separate DOM from game Logic

2020-09-10 10:48 UTC, rOluochKe requested changes
Hello @bouaik 
### Good job you have done so far :clap: However, you have a few issues you need to fix:-
- [ ] Separating dom from app logic means having two files for logic and dom
- [ ] Update your readme on how one can install the project and play the game
### Make the changes and submit for another code review. Good luck
- Happy coding!

### [Optional]
- You can use localStorage to store users scores

By Raymond
Slack @iamraymond

2020-09-10 10:49 UTC, rOluochKe commented on app.js
> +})();
### Take the dom in a separate file

2020-09-10 11:24 UTC, rOluochKe approved these changes
### You got it right. The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

### [Optional]
- Create a directory, src and put your development files inside for easy readability and maintenance

2020-09-10 15:27 UTC, merged